# Generated by Django 5.0.6 on 2024-10-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="https://bxboavniaetazfvskxln.supabase.co/storage/v1/object/sign/devsearch-default/user-default.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJkZXZzZWFyY2gtZGVmYXVsdC91c2VyLWRlZmF1bHQucG5nIiwiaWF0IjoxNzI5ODY2MDU2LCJleHAiOjMzMDY2NjYwNTZ9.rISieoKeFQPFOFObgx6fzlkWxp5Ef0oTprEmbg5fNCc&t=2024-10-25T14%3A20%3A55.434Z",
                null=True,
                upload_to="",
            ),
        ),
    ]
