# Generated by Django 5.0.6 on 2024-10-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                default="https://bxboavniaetazfvskxln.supabase.co/storage/v1/object/sign/devsearch-default/project-default.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJkZXZzZWFyY2gtZGVmYXVsdC9wcm9qZWN0LWRlZmF1bHQuanBnIiwiaWF0IjoxNzI5ODY2MjE3LCJleHAiOjMzMDY2NjYyMTd9.xPVSBjTzb1xVuPWXBXSaM08bzq7C6SBfoCa_HAG9Cx4&t=2024-10-25T14%3A23%3A36.186Z",
                null=True,
                upload_to="",
            ),
        ),
    ]
