# Generated by Django 5.0.6 on 2024-11-01 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_recipient_alter_chatmessage_sender'),
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.profile'),
        ),
    ]
